name: Rust Action

on:
  push:
    branches:
      - main

jobs:
  format:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format code
        run: cargo fmt --manifest-path rtop/Cargo.toml

      - name: Check formatting
        run: cargo check --manifest-path rtop/Cargo.toml

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build code
        run: cargo build --release --manifest-path rtop/Cargo.toml

      - name: Check build
        run: cargo check --release --manifest-path rtop/Cargo.toml

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --release --manifest-path rtop/Cargo.toml

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Rusted release of HTOP for platforms
